[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "BMI-Stuff"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.4,<3"
plotly = ">=6.0.1,<7"
scipy = ">=1.15.2,<2"
ipywidgets = ">=8.1.5,<9"
ipython = ">=9.0.2,<10"
jupyter = ">=1.1.1,<2"
